blog/about/urls.py
from django.urls import path

from .views import AboutAuthorView, AboutProjectView

app_name = 'about'

urlpatterns = [
    path('project/', AboutProjectView.as_view(), name='about_project'),
    path('me/', AboutAuthorView.as_view(), name='about_me')
]

blog/blog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include('notes.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('about/', include('about.urls')),
    path('users/', include('users.urls')),
    path('users/accounts/', include('django.contrib.auth.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

blog/notes/urls.py
from django.urls import path
from . import views

app_name = "notes"

urlpatterns = [
	path('', views.index, name='index'),
	path("<int:article_id>/", views.detail, name="detail"),
	path("<int:article_id>/results/", views.results, name="results"),
    path("<int:article_id>/comment/", views.comment, name="comment"),
	path("add_article", views.add_article, name='add_article'),
    path("edit_article/<int:article_id>", views.edit_article, name='edit_article'),
	path('delete_article/<int:article_id>', views.delete_article, name='delete_article'),
	path('article/<int:article_id>/unlock', views.unlock_article, name='unlock_article'),
]

blog/users/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views

app_name = 'users'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('singup/', views.signup, name='signup'),
]

blog/templates/layout.html
{% load static %}
{% load bootstrap_icons %}

<!DOCTYPE html>
<html lang="en">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mind space</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'notes/main_style.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap_icons/css/bootstrap_icons.css' %}">
    {% block includes %}
    {% endblock includes %}
</html>

<body>
    <header class="header">
        <div class="logo item1">
            <a id="logo-anchor" href="{% url 'notes:index' %}">
                Тошнота
            </a>
        </div>
        <div class="item2">
            <a href="{% url 'notes:add_article' %}" class="blink"><i class="bi bi-pen middle-icon"></i></a>
        </div>
        <div class="item3">
            <a href="{% url 'users:profile' %}" class="blink"><i class="bi bi-person-circle middle-icon"></i></a>
        </div>
        <nav class="nav item4 dropdown">
            <button href="#menu" class="blink dropbtn">
                <i class="bi bi-list large-icon"></i>
            </a>
            <div class="dropdown-content">
                <a href="{% url 'about:about_me' %}">О нас</a>
                <a href="{% url 'about:about_project' %}">О проекте</a>
            </div>
        </nav>
        
    </header>
    <main>
        {% block content %}
        {% endblock %}

    </main>

</body>