blog/blog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include('notes.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('about/', include('about.urls')),
    path('users/', include('users.urls')),
    path('users/accounts/', include('django.contrib.auth.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

blog/notes/urls.py
from django.urls import path
from . import views

app_name = "notes"

urlpatterns = [
	path('', views.index, name='index'),
	path("<int:article_id>/", views.detail, name="detail"),
	path("<int:article_id>/results/", views.results, name="results"),
    path("<int:article_id>/comment/", views.comment, name="comment"),
	path("add_article", views.add_article, name='add_article'),
    path("edit_article/<int:article_id>", views.edit_article, name='edit_article'),
	path('delete_article/<int:article_id>', views.delete_article, name='delete_article'),
	path('article/<int:article_id>/unlock', views.unlock_article, name='unlock_article'),
]

blog/notes/models.py
from django.db import models
from markdownx.models import MarkdownxField
from tinymce.models import HTMLField
from django.contrib.auth.models import User

class Partition(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return str(self.name)

class Chapter(models.Model):
    partition = models.ForeignKey(Partition, models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return str(self.name)


class Article(models.Model):
    chapter = models.ForeignKey(Chapter, models.SET_NULL, blank=True, null=True)
    heading = models.CharField(max_length=200)
    body = HTMLField()
    pub_date = models.DateTimeField(auto_now_add=True)
    last_edit_date = models.DateTimeField(auto_now=True)
    image = models.ImageField(
        verbose_name='Изображение',
        upload_to='articles/',
        blank=True,
    )
    authors = models.ManyToManyField(User, related_name='articles')

    # блокировка модели
    is_locked = models.BooleanField(default=False)
    locked_by = models.ManyToManyField(User, blank=True, default=None)

    def __str__(self) -> str:
        return str(self.heading)

blog/notes/forms.py
from markdownx.fields import MarkdownxFormField
from django import forms
from .models import Chapter, Article
from tinymce.widgets import TinyMCE

class MyForm(forms.Form):
    myfield = MarkdownxFormField()

class ArticleWriteForm(forms.ModelForm):
    chapter = forms.ModelChoiceField(queryset=Chapter.objects.all())
    heading = forms.CharField(max_length=200, required=True)
    body = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30, 'id': 'tiny'}))
    image = forms.ImageField(
                widget=forms.ClearableFileInput(attrs={'accept': 'image/*'}), required=False
    )

    class Meta:
        model = Article
        fields = ('chapter', 'heading', 'body', 'image')

blog/notes/views.py
from django.shortcuts import HttpResponse, render, get_object_or_404, redirect
from django.contrib.auth.decorators import permission_required

from .paginator import paginator
from .models import Article, Partition, Chapter
from .forms import ArticleWriteForm
from django.http import HttpResponseForbidden, JsonResponse
from django.views.decorators.csrf import csrf_exempt

def index(request):
    articles = Article.objects.order_by('-pub_date')
    
    latest_articles_list = Article.objects.order_by("-pub_date")[:2]
    context = {
        "articles": paginator(request, articles, 8),
        "latest_articles_list": latest_articles_list,
        'user': request.user,
    }

    return render(request, "notes/index.html", context)

def detail(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    context = {
        "art": article,
    }
    return render(request, "notes/detail.html", context)

def results(request, article_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % article_id)


def comment(request, article_id):
    return HttpResponse("You're commenting on question %s." % article_id)

@permission_required('notes.change_article', raise_exception=True)
def edit_article(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    if (not article.authors.filter(id=request.user.id).exists()):
        return HttpResponseForbidden("Вы не являетесь автором данного поста")
    condition = (article.is_locked)
    if (condition and (not article.locked_by.filter(id=request.user.id).exists())):
        return HttpResponseForbidden("Статья редактируется другим пользователем")

    article.is_locked = True
    article.locked_by.add(request.user.id)
    article.save()

    if request.method == 'POST':
        form = ArticleWriteForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            article.is_locked = False
            article.locked_by.clear()
            article.save()
            return redirect('notes:detail', article_id = article.id)
    else:
        initial_data = {
            'chapter' : article.chapter,
            'heading' : article.heading,
            'body': article.body,
        }
        form = ArticleWriteForm(initial=initial_data)
    return render(request, "notes/edit_article.html", {'form': form})

@permission_required('notes.add_article', raise_exception=True)
def add_article(request):
    if request.method == 'POST':
        form = ArticleWriteForm(request.POST, request.FILES)
        if form.is_valid():
            article = Article(
                chapter = form.cleaned_data['chapter'],
                heading = form.cleaned_data['heading'],
                body = form.cleaned_data['body'],
                image = form.cleaned_data['image'],
            )
            article.save()
            article.authors.add(request.user)
            return redirect('notes:index')
    else:
        form = ArticleWriteForm()
    return render(request, 'notes/add_article.html', {'form': form})

@permission_required('notes.delete_article', raise_exception=True)
def delete_article(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    if not article.authors.filter(id=request.user.id).exists():
        return HttpResponseForbidden("Вы не можете удалить данный пост, так как вы не являетесь одним из его создателей")
    if request.method == 'POST':
        article.delete()
        return redirect('notes:index')
    
@csrf_exempt
def unlock_article(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    article.is_locked = False
    article.locked_by = None
    article.save()
    return JsonResponse({'status' : 'success'})

blog/templates/notes/add_article.html
{% extends "layout.html"%}
{% load static %}

{% block includes %}
{{form.media}}
<link ref="stylesheet" href="{% static 'notes/add_note.css '%}">
{% endblock includes %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить</button>
</form>
{% endblock %}

blog/templates/notes/detail.html
{% extends "layout.html"%}
{% load static %}

{% block includes %}
<link rel="stylesheet" href="{% static 'notes/main_style.css' %}">
<link rel="stylesheet" href="{% static 'notes/detail_notes.css' %}">
{% endblock %}

{% block content %}
{% if art %}
    <h1 class="left-moved upper_case">{{ art.heading }} </h1>
    <div class="left-moved" name="note_detail_body">{{art.body |safe}}</div>
    <p>Авторы:
        {% for author in art.authors.all %}
            {{ author.first_name }} {{author.last_name}}{% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>
<p>{{ article.content }}</p>
    <p name="pub_date" class="left-moved">Дата публикации: {{art.pub_date}}</p>
    <p name="last_edit_date" class="left-moved">Дата последнего изменения: {{art.last_edit_date}}</p>

{% endif %}

{% endblock %}

blog/templates/notes/edit_article.html
{% extends 'layout.html' %} 
{% load static%}
{% block includes %}
    {{form.media}}
{% endblock includes %}

{% block content %}
<script src="{% static 'js/unlock_note.js' %}"></script>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

blog/templates/notes/index.html
{% extends 'layout.html' %}
{% load static %}
{% load custom_filters %}

{% block includes %}
<link rel="stylesheet" href="{% static 'notes/index_styles.css' %}">
{% endblock %}

{% block content %}
<p style="text-align: center;">«Desine sperare qui hic intras» — Оставь надежду всяк сюда входящий</p>
<h5>
    Недавние выпуски:
</h5>
{% if latest_articles_list %}
    <div class="cards">
        {% for article in latest_articles_list %}
            <a href="{% url 'notes:detail' article.id %}">
                <div class="card-box">
                {% if article.image %}
                    <img class="fit-size" src="{{ article.image.url }}" />
                {% else %}
                    <div class="fit-size linear-gradient"></div>
                {% endif %}
                    <div class="overlay-text">{{ article.heading}}</div>
                    <div class="appearing-text">{{article.body | bleach_clean | truncatechars:100}}</div>
                </div>
            </a>
        {% endfor %}
    </div>
{% else %}
    <p>No articles are available</p>
{% endif %}
<h5>
    Выпуски:
</h5>


<div class="cards">
    {% for elem in articles %}
        <article>
            <a href="{% url 'notes:detail' elem.id %}">
                <div class="card-box">
                    {% if elem.image %}
                        <img class="fit-size" src="{{ elem.image.url }}" />
                    {% else %}
                        <div class="fit-size linear-gradient"></div>
                    {% endif %}
                    <div class="overlay-text">{{ elem.heading}}</div>
                    <div class="appearing-text">{{elem.body | bleach_clean | truncatechars:100}}</div>
                </div>
                {% if user.is_authenticated %}
                <div class="horizontal">
                    <div class="bordered background-blink common-width"><a href="{% url 'notes:edit_article' elem.id %}"><i class="bi bi-pencil"></i> Редактировать</a></div>
                    <form method="post" onsubmit="return confirm('Вы уверены, что хотите удалить эту статью?');" action="{% url 'notes:delete_article' elem.id %}">
                        {% csrf_token %}
                        <div id="left"><button type="submit" class="bordered background-blink white-text fulls-filled" ><i class="bi bi-trash"></i> Удалить</button></div>
                    </form>
                </div>
                {%endif%}
            </a>
        </article>
    {% endfor %}
</div>
{% endblock %}